---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Main
- type: document
  path: category.html
  label: Main Page (Category)
- type: heading
  label: Portfolio
- type: heading
  label: Posts_HTML
- type: directory
  path: posts_HTML
  label: Posts_HTML
  create: all
  match: "**/*"
- type: heading
  label: Posts_Python
- type: directory
  path: posts_python
  label: Posts_Python
  create: all
  match: "**/*"
- type: heading
  label: Posts_HCI
- type: directory
  path: posts_HCI
  label: Posts_HCI
  create: all
  match: "**/*"
- type: heading
  label: Posts_ML & AI
- type: directory
  path: posts_ML&AI
  label: Posts_ML & AI
  create: all
  match: "**/*"
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
